name: Deploy to SFTP Server

on:
  push:
    branches: [ prod ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Deploy via SFTP
      uses: pressidium/lftp-mirror-action@v1
      with:
        host: ${{ secrets.FTP_SERVER }}
        user: ${{ secrets.FTP_USERNAME }}
        pass: ${{ secrets.FTP_PASSWORD }}
        settings: 'sftp:auto-confirm yes'
        localDir: './'
        remoteDir: '/public_html/'
        options: '--verbose --reverse --delete --exclude .git/ --exclude .github/ --exclude README.md'
